MODEL: "RF"
TUNE_HP_PARAMS: False
RF:
  n_estimators: 10
  criterion: "entropy" # {"gini", "entropy"}
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "auto" # {"auto", "sqrt", "log2"}
  n_jobs: -1
  random_state: 0
  ccp_alpha: 0.2

INPUT:
  PATH: "./data/ns10_ls300_normalized.npz"
  CAT_TRAIN_VAL: True

OUTPUT_DIR: "./output"
