MODEL: "RF"
TUNE_HP_PARAMS: True
RF:
  n_estimators: [10, 100, 1000] # [10, 100, 1000]
  criterion: ["gini", "entropy"] # ["gini", "entropy"]
  max_depth: [None, 10, 20, 30] # [None, 10, 20, 30]
  min_samples_split: [2, 4, 6] # [2, 4, 6]
  min_samples_leaf: [1, 2, 3] # [1, 2, 3]
  max_features: ["auto", "sqrt", "log2"] # ["auto", "sqrt", "log2"]
  n_jobs: [-1] # [-1]
  ccp_alpha: [0.0, 0.2, 0.4, 0.6] # [0.0, 0.2, 0.4, 0.6]
  random_state: [null]

INPUT:
  PATH: "./data/ns10_ls300_normalized.npz"
  CAT_TRAIN_VAL: False

OUTPUT_DIR: "./output"
