MODEL: "RF"
TUNE_HP_PARAMS: True
RF:
  # n_estimators: 100
  # criterion: "gini" # {"gini", "entropy"}
  # max_depth: 20
  # min_samples_split: 2
  # min_samples_leaf: 1
  # max_features: "auto" # {"auto", "sqrt", "log2"}
  # n_jobs: -1
  # ccp_alpha: 0.0
  random_state: null

INPUT:
  PATH: "./data/ns10_ls300_normalized.npz"
  CAT_TRAIN_VAL: False

OUTPUT_DIR: "./output"
