MODEL: "SVM"
TUNE_HP_PARAMS: True
SVM:
  # C: 7.0
  # kernel: "rbf" # {"linear", "poly", "rbf", "sigmoid", "precomputed"}
  # degree: 1
  # gamma: "scale" # {"scale", "auto"} or float
  # class_weight: null
  # decision_function_shape: "ovo" # {"ovo", "ovr"}
  random_state: null

INPUT:
  PATH: "./data/ns10_ls300_normalized.npz"
  CAT_TRAIN_VAL: False

OUTPUT_DIR: "./output"
