MODEL: "SVM"
TUNE_HP_PARAMS: True
SVM:
  # -----------------------------------------------------------------------------
  # Support Vector Machine
  # For full documentation, please see:
  # https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
  # -----------------------------------------------------------------------------
  C: np.linspace(1, 10, num=10).tolist()
  kernel: ["linear", "rbf", "poly", "sigmoid"]
  degree: list(range(1, 6))
  gamma: ["scale", "auto"]
  class_weight: ["balanced", null]
  decision_function_shape: ["ovo", "ovr"]
  random_state: null

INPUT:
  PATH: "./data/ns10_ls300_normalized.npz"
  CAT_TRAIN_VAL: False

OUTPUT_DIR: "./output"
